sudo: false

language: node_js
node_js:
  - "stable"
  - "8"
  - "6"
  - "4"

matrix:
  fast_finish: true


branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - yarn test
