---
before_install:
    # if npm version is less than 3.0.0, upgrade to 3
    - if [[ $(npm -v | cut -d '.' -f 1) -lt 3 ]]; then npm i -g npm@^3; fi
language: node_js
node_js:
  - "stable"
  - "6"
  - "4"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
